pipeline {

    agent any

    tools {

        maven 'My Maven'
    }

    stages {

        stage('Build') {

            steps {
                
                sh "mvn clean package"
            }
            post {

                success {

                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
    }
}